//! Command-spec completion — subcommands + options for known CLIs.
//!
//! Source: `apps/desktop/src-tauri/completion-specs/bundle.json`, which
//! is generated by `scripts/import-fig-specs.mjs` from the MIT-licensed
//! `withfig/autocomplete` TypeScript specs. Credit: Fig + all autocomplete
//! contributors. See scripts/import-fig-specs.mjs for exactly which
//! static fields we keep (name/description/subcommands[]/options[]) and
//! what we drop (runtime generators, postProcess callbacks, conditional
//! arg definitions — anything that would require executing JS).
//!
//! Flow at runtime:
//!
//!   1. `try_complete(text, cursor)` examines the editor text.
//!   2. Walks the tokens before the cursor; the first token is the root
//!      command (e.g. `git`). If we have a spec for it, we descend into
//!      that spec's subcommand tree using each remaining full token to
//!      pick a more-specific child (e.g. `git remote add` lands us on
//!      `add`'s subcommand).
//!   3. The PARTIAL token (the one being actively typed when Tab fires)
//!      becomes the filter: we match it against the current spec's
//!      subcommand names + option names.
//!   4. Returns Some(CompletionResult) if any matches; None if we don't
//!      know the root command, so the caller falls back to filesystem
//!      completion.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

use super::fs::{Completion, CompletionKind, CompletionResult};

/// The entire spec bundle compiled into the binary. ~1.7 MB of JSON;
/// include_str! adds it to the `.rodata` section. Parsed exactly once
/// at first access via OnceLock. If parsing fails (malformed JSON),
/// `registry()` logs and returns an empty map — completion degrades to
/// filesystem only, we don't crash.
const BUNDLE_JSON: &str =
    include_str!("../../completion-specs/bundle.json");

/// Command spec = the root-level entry for a CLI (e.g. `git`). Identical
/// shape to nested `subcommands` entries; we reuse the same struct for
/// both roots and subcommands because the Fig schema is recursive.
#[derive(Debug, Clone, Deserialize)]
pub struct CommandSpec {
    /// All names this command answers to. First entry is canonical.
    #[serde(default)]
    pub names: Vec<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub subcommands: Vec<CommandSpec>,
    #[serde(default)]
    pub options: Vec<OptionSpec>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OptionSpec {
    /// Flag names (`-v`, `--verbose`). Fig sometimes lists both short
    /// and long here; we treat each as its own completion entry so the
    /// user can pick whichever fits.
    #[serde(default)]
    pub names: Vec<String>,
    #[serde(default)]
    pub description: Option<String>,
}

/// Return the command → spec map, parsed lazily.
fn registry() -> &'static HashMap<String, CommandSpec> {
    static CELL: OnceLock<HashMap<String, CommandSpec>> = OnceLock::new();
    CELL.get_or_init(|| match serde_json::from_str::<HashMap<String, CommandSpec>>(BUNDLE_JSON) {
        Ok(map) => {
            log::info!(
                "completion specs loaded: {} commands",
                map.len()
            );
            map
        }
        Err(e) => {
            log::warn!(
                "completion specs parse failed ({e}); running with FS-only completion"
            );
            HashMap::new()
        }
    })
}

/// Entry point called by completion::complete. Returns Some(result) if
/// the editor text is completing against a known command; None lets the
/// caller fall back to filesystem completion.
pub fn try_complete(text: &str, cursor_pos: usize) -> Option<CompletionResult> {
    let cursor_pos = cursor_pos.min(text.len());

    // Tokenize the text up to cursor. Anything after the cursor is
    // irrelevant — the user hasn't touched it, and completing against
    // the full string would confuse the logic when they Tab mid-line.
    let prefix = &text[..cursor_pos];
    let tokens = tokenize(prefix);

    // Need at least two tokens (root command + something being typed)
    // to do spec completion. If there's only one token, it's the
    // command itself — filesystem (PATH binaries) is the right source,
    // which is what the fallback does today.
    if tokens.len() < 2 {
        return None;
    }

    let root_name = tokens[0].text;
    let reg = registry();
    let root = reg.get(root_name)?;

    // Descend through the subcommand tree using all tokens EXCEPT the
    // last (which is partial/in-progress). Each fully-typed token picks
    // a more specific spec if one exists; unknown tokens break the
    // chain (we can't assume what they refer to).
    let mut current: &CommandSpec = root;
    for t in &tokens[1..tokens.len() - 1] {
        match find_subcommand(current, t.text) {
            Some(next) => current = next,
            None => break, // unknown arg; still complete against `current`
        }
    }

    // The in-progress token drives the filter. token_start/token_end are
    // byte offsets into the original text so the frontend can splice in
    // the replacement without re-deriving positions.
    let partial = &tokens[tokens.len() - 1];
    let filter = partial.text;

    let mut completions: Vec<Completion> = Vec::new();

    // Options starting with `-` always beat subcommands when the partial
    // begins with `-` — this matches every shell's tab-completion norm
    // (`git --ver<Tab>` should find `--version`, not a subcommand).
    let looking_for_option = filter.starts_with('-');

    if !looking_for_option {
        for sc in &current.subcommands {
            for name in &sc.names {
                if name.starts_with(filter) {
                    completions.push(Completion {
                        label: name.clone(),
                        replacement: name.clone(),
                        kind: CompletionKind::Subcommand,
                        hidden: false,
                        description: sc.description.clone(),
                    });
                }
            }
        }
    }

    for opt in &current.options {
        for name in &opt.names {
            if name.starts_with(filter) {
                completions.push(Completion {
                    label: name.clone(),
                    replacement: name.clone(),
                    kind: CompletionKind::Option,
                    hidden: false,
                    description: opt.description.clone(),
                });
            }
        }
    }

    // Stable sort: shorter names first (e.g. `-v` before `--verbose`,
    // and `add` before `add-remote`). Keeps the most-common option at
    // the top when both a short and long alias match.
    completions.sort_by(|a, b| {
        a.label
            .len()
            .cmp(&b.label.len())
            .then_with(|| a.label.cmp(&b.label))
    });

    if completions.is_empty() {
        return None;
    }

    Some(CompletionResult {
        token_start: partial.start,
        token_end: cursor_pos,
        completions,
    })
}

/// Look up a subcommand of `parent` by name (matches any alias).
fn find_subcommand<'a>(parent: &'a CommandSpec, name: &str) -> Option<&'a CommandSpec> {
    parent
        .subcommands
        .iter()
        .find(|sc| sc.names.iter().any(|n| n == name))
}

/// Splits text into non-empty whitespace-delimited tokens with their
/// byte offsets. Mirrors the tokenizer in fs::extract_token but returns
/// ALL tokens, not just the one under the cursor.
struct Token<'a> {
    text: &'a str,
    start: usize,
}

fn tokenize(text: &str) -> Vec<Token<'_>> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        // Skip whitespace.
        while i < bytes.len() && matches!(bytes[i], b' ' | b'\t' | b'\n') {
            i += 1;
        }
        if i >= bytes.len() {
            break;
        }
        let start = i;
        while i < bytes.len() && !matches!(bytes[i], b' ' | b'\t' | b'\n') {
            i += 1;
        }
        out.push(Token {
            text: &text[start..i],
            start,
        });
    }
    // If the text ends with whitespace, the user started a NEW token
    // after it — represent that as an empty token so partial filtering
    // works with an empty filter (shows everything).
    if !bytes.is_empty() && matches!(bytes[bytes.len() - 1], b' ' | b'\t' | b'\n') {
        out.push(Token {
            text: "",
            start: bytes.len(),
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// SECURITY (Wave 4): the Fig bundle is a ~10 MB committed JSON
    /// artifact generated by `scripts/import-fig-specs.mjs`. An
    /// attacker (or careless reviewer) could land a PR that hand-edits
    /// `bundle.json` directly, bypassing the AST walker's "only static
    /// literals" guarantee. This test catches the most visible tamper
    /// shapes:
    ///   - bundle truncated / wiped entirely
    ///   - parse-breaking edits (malformed JSON)
    ///   - wholesale replacement with a tiny or empty map
    ///   - common root commands removed (someone editing to hide git,
    ///     docker, npm entries)
    ///
    /// It doesn't catch targeted injection into a single command's
    /// option description — that requires the regen-from-source CI
    /// step, which is a follow-up.
    #[test]
    fn bundle_parses_and_has_expected_commands() {
        let registry = registry();
        assert!(
            registry.len() > 500,
            "Fig bundle shrank unexpectedly ({} entries); \
             expected >500. Possible hand-edit or truncated commit.",
            registry.len()
        );

        // Canary commands — if any of these disappear from the bundle,
        // something went wrong in the import or the bundle was
        // tampered with. Chosen because they're among the most-used
        // CLIs in terminal sessions.
        let canaries = &[
            "git", "docker", "npm", "cargo", "kubectl", "ssh", "brew",
            "curl", "aws", "python",
        ];
        for name in canaries {
            assert!(
                registry.contains_key(*name),
                "Fig bundle missing canary command '{}' — \
                 possible tamper or import regression",
                name
            );
        }
    }
}
